language: php
php:
  - '5.6'
  - '7.0'
matrix:
  fast_finish: true
sudo: false
before_script:
  - phpenv config-rm xdebug.ini
  - composer install --prefer-source
  - vendor/bin/sculpin generate
  - vendor/bin/sculpin serve &
script:
  # Run the tests!
  - vendor/bin/behat --config travis-behat.yml

